//
// Created by inkih on 30/11/25.
//

#ifndef POKEMONGAMEENGINE_COMPONENTSTYPE_H
#define POKEMONGAMEENGINE_COMPONENTSTYPE_H

enum class ComponentsType {
    POSITION,
    RENDER,
    COLLIDER,
    ANIMATION,
    MOVEMENT,
    SCRIPT,
    INTERACTION,
    PERSISTENCE,
};

#endif //POKEMONGAMEENGINE_COMPONENTSTYPE_H